# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

swift_version:
  - 3.0
target:
  # - osx # passing
  # - docs # passing
  # - ios-static # passing
  # - ios-dynamic # passing
  - ios-swift
  # - osx-swift # passing
  - watchos
  - cocoapods
  # - swiftlint # passing
  - tvos
  # - osx-encryption # passing
  # FIXME: Re-enable device tests when they can be made to run reliably
  # - ios-device-objc
  # - ios-device-swift
  # - tvos-device
configuration:
  # - Debug
  - Release

# exclude:
#   - target: ios-device-objc
#     configuration: Debug
#   - target: ios-device-swift
#     configuration: Debug
#   - target: docs
#     configuration: Debug
#   - target: cocoapods
#     configuration: Debug
#   - target: swiftlint
#     configuration: Debug
#   - target: tvos-device
#     configuration: Debug
